language: node_js
node_js:
   - "v8.5.0"
branches:
  only:
  - master
  - develop
  - features/plws-8-setup-continuous-deployment-to-aws

before_script:
  - npm install -g bower
  - bower install

notifications:
  email:
    recipients:
      - kenneth_flow@hotmail.com
    on_success: change # default: change
    on_failure: always # default: always

jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy
      script: npm deploy:aws:lambda
    - stage: pre-deploy
      script: npm build:aws:deployment-package $TRAVIS_BRANCH $TRAVIS_COMMIT
stages:
  - test
  - pre-deploy
  - name: deploy
    if: branch = features/plws-8-setup-continuous-deployment-to-aws