language: node_js
node_js:
   - "v8.5.0"
branches:
  only:
  - master
  - develop

before_script:
  - npm install -g bower
  - bower install

notifications:
  email:
    recipients:
      - kenneth_flow@hotmail.com
    on_success: change # default: change
    on_failure: always # default: always