language: node_js
node_js:
   - "v8.5.0"
branches:
  only:
  - master
  - develop

notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: change # default: change
    on_failure: always # default: always
